### ISSUE TITLE
PCK Certificate parsing fails (version 2.0.1)

### ISSUE THREAD

**Issue by ThorodanBrom** [Cosmian/intel-sgx-ra#7]
Hello,

When trying to verify a quote from SGX in `processor` mode, we're getting the error `SGX PCK parsing failed`. We can confirm that the quote itself is valid.

We're not sure where the error is coming from as the string is not present in the repo. If required (and if it's safe to do so), we can share the PCK certificate or quote that's causing the issue.

Many thanks!

**Comment by grydz** [comment]
Thanks for pointing out the bug when the PCK certificate is issued by PCK Processor CA.

Let me know if version [2.1.0](https://pypi.org/project/intel-sgx-ra/2.1.0/) solves your issue.

**Comment by ThorodanBrom** [comment]
Hello @grydz 

Thanks for the quick fix. The `SGX PCK parsing failed` error is solved on **2.1.0**, but we get a `KeyError` error for `tcb-info-issuer-chain`. I'm not sure if this is an issue on our end, or if this is related to the PCK parsing issue. If it helps, the quote is of `processor` type and the PCCS URL is `https://pccs.mse.cosmian.com`

![Screenshot_2023-10-13_11-18-04](https://github.com/Cosmian/intel-sgx-ra/assets/9331293/89ed7d8e-989c-4359-bf3a-9f2576098ab1)

Many thanks!

**Comment by grydz** [comment]
> Hello @grydz
> 
> Thanks for the quick fix. The `SGX PCK parsing failed` error is solved on **2.1.0**, but we get a `KeyError` error for `tcb-info-issuer-chain`. I'm not sure if this is an issue on our end, or if this is related to the PCK parsing issue. If it helps, the quote is of `processor` type and the PCCS URL is `https://pccs.mse.cosmian.com`
> 
> ![Screenshot_2023-10-13_11-18-04](https://user-images.githubusercontent.com/9331293/274808040-89ed7d8e-989c-4359-bf3a-9f2576098ab1.png)
> 
> Many thanks!

The error is not the expected one but it fails for a good reason: the URL `https://pccs.mse.cosmian.com` is the default PCCS URL in our infrastracture for one of our [product](https://docs.cosmian.com/microservice_encryption/overview/). Because your SGX machine is not part of our infrastructure, it should fail before checking the HTTP headers in the response.

If you are using Microsoft Azure, you can use this specific function [verify_quote()](https://github.com/Cosmian/intel-sgx-ra/blob/main/src/intel_sgx_ra/maa/attest.py#L119) which requests [Microsoft Azure Attestation service API](https://learn.microsoft.com/en-us/rest/api/attestation/attestation/attest-sgx-enclave). If you are using your own SGX infrastructure, you should run your own PCCS to register your SGX machine (see [Design Guide for Intel SGX PCCS](https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/SGX_DCAP_Caching_Service_Design_Guide.pdf)).

I'll fix this to raise the correct exception.

**Comment by ThorodanBrom** [comment]
Hello @grydz 

Many thanks for the clarification. We are currently using our own SGX machine, so we'll look into setting up our own PCCS.
